id: P005615
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20820
  title: ལྷོ་ཁའི་རྩོམ་རིག་སྒྱུ་རྩལ། ༼དུས་དེབ།༽
  author: ''
  volumes:
    554e5698f7d44ccaac998a78fd4bac79:
      image_group_id: I1KG14479
      title: ''
      volume_number: 51
      total_pages: 94
      base_file: v001.txt
    5b967870dd6c4548b5fd3bd63331d763:
      image_group_id: I1PD36073
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v002.txt
    e8492b8e9e2d479eb16b684be893dc75:
      image_group_id: I1PD36074
      title: ''
      volume_number: 2
      total_pages: 118
      base_file: v003.txt
    1bd5bf1eb2554d9fa32450e812625345:
      image_group_id: I1PD36075
      title: ''
      volume_number: 3
      total_pages: 150
      base_file: v004.txt
    f5d62c0b7ff04862a3c600ba440b3b93:
      image_group_id: I1PD36076
      title: ''
      volume_number: 4
      total_pages: 94
      base_file: v005.txt
    35e96f3a201e4e17aa0b3790211be265:
      image_group_id: I1PD36077
      title: ''
      volume_number: 5
      total_pages: 98
      base_file: v006.txt
    a134cd83d8a94ed0b7ca37a5194fcf88:
      image_group_id: I1PD36078
      title: ''
      volume_number: 6
      total_pages: 128
      base_file: v007.txt
    d52353ca95554808bac394ccce379db9:
      image_group_id: I1PD36079
      title: ''
      volume_number: 7
      total_pages: 154
      base_file: v008.txt
    daf38e71bbea492980901b5c593ae467:
      image_group_id: I1PD36080
      title: ''
      volume_number: 8
      total_pages: 134
      base_file: v009.txt
    103f82b078594376a02940a50083cc7c:
      image_group_id: I1PD36081
      title: ''
      volume_number: 9
      total_pages: 86
      base_file: v010.txt
    d2e4e4327fb3482ab38ed4fcc8df71c7:
      image_group_id: I1PD36082
      title: ''
      volume_number: 10
      total_pages: 110
      base_file: v011.txt
    9e571417995742339a6aeb635ac53023:
      image_group_id: I1PD36083
      title: ''
      volume_number: 11
      total_pages: 98
      base_file: v012.txt
    c5c8028bbde14e47a163b5b848523d60:
      image_group_id: I1PD36084
      title: ''
      volume_number: 12
      total_pages: 90
      base_file: v013.txt
    e50288ee3c73403f9b6d587a9a80a262:
      image_group_id: I1PD36085
      title: ''
      volume_number: 13
      total_pages: 84
      base_file: v014.txt
    3c19dcbf3bbd415f95861e732ead4409:
      image_group_id: I1PD36086
      title: ''
      volume_number: 14
      total_pages: 88
      base_file: v015.txt
    066c4ea74dac473fa8203d8897548a82:
      image_group_id: I1PD36087
      title: ''
      volume_number: 15
      total_pages: 94
      base_file: v016.txt
    1f25517c85924a81b233f001d7064b7f:
      image_group_id: I1PD36088
      title: ''
      volume_number: 16
      total_pages: 84
      base_file: v017.txt
    9bf874c19aa5415e873d2d7a7d4df122:
      image_group_id: I1PD36089
      title: ''
      volume_number: 17
      total_pages: 94
      base_file: v018.txt
    2068fbc4cf44418faf42308dbe5d77df:
      image_group_id: I1PD36090
      title: ''
      volume_number: 18
      total_pages: 92
      base_file: v019.txt
    143b664ff54f4e7eb4c793d3c50ab673:
      image_group_id: I1PD36091
      title: ''
      volume_number: 19
      total_pages: 84
      base_file: v020.txt
    ddcb7a7d8c4d47baab6d9610150b3fde:
      image_group_id: I1PD36092
      title: ''
      volume_number: 20
      total_pages: 96
      base_file: v021.txt
    e30a4fc0ab5f47c3ba7307dd9ae674af:
      image_group_id: I1PD36093
      title: ''
      volume_number: 21
      total_pages: 96
      base_file: v022.txt
    98f1b14985db451082c324c5fa693dc6:
      image_group_id: I1PD36094
      title: ''
      volume_number: 22
      total_pages: 100
      base_file: v023.txt
    2f9b534b5eab4840b741a623b1653e0f:
      image_group_id: I1PD36095
      title: ''
      volume_number: 23
      total_pages: 126
      base_file: v024.txt
    79f0f1c3cf374acaaec1ce8a989076bc:
      image_group_id: I1PD36096
      title: ''
      volume_number: 24
      total_pages: 122
      base_file: v025.txt
    5110be61c0f14a7bbd926dbc2ed6f22f:
      image_group_id: I1PD36097
      title: ''
      volume_number: 25
      total_pages: 94
      base_file: v026.txt
    d013717130fc45feaeffe1cbf7b0345c:
      image_group_id: I1PD36098
      title: ''
      volume_number: 26
      total_pages: 134
      base_file: v027.txt
    252028b1421b4f039b861dd619378217:
      image_group_id: I1PD36099
      title: ''
      volume_number: 27
      total_pages: 118
      base_file: v028.txt
    813949789e4c4d4984652220ce132c88:
      image_group_id: I1PD36100
      title: ''
      volume_number: 28
      total_pages: 118
      base_file: v029.txt
    81768d7f38ec469ba3e42bd21748cd2c:
      image_group_id: I1PD36101
      title: ''
      volume_number: 29
      total_pages: 86
      base_file: v030.txt
    635c30f95d4e4e70ace3abd0e420944f:
      image_group_id: I1PD36102
      title: ''
      volume_number: 30
      total_pages: 94
      base_file: v031.txt
    e902e04f8e364865b713ebf343d46dba:
      image_group_id: I1PD36103
      title: ''
      volume_number: 31
      total_pages: 88
      base_file: v032.txt
    ff951581bb09485d882a96d14764d06a:
      image_group_id: I1PD36104
      title: ''
      volume_number: 32
      total_pages: 86
      base_file: v033.txt
    3580411bd5054f4f912d14bde06378e6:
      image_group_id: I1PD36105
      title: ''
      volume_number: 33
      total_pages: 82
      base_file: v034.txt
    4c0bb9c6214a4d7ca7d84727bdf843ac:
      image_group_id: I1PD36106
      title: ''
      volume_number: 34
      total_pages: 86
      base_file: v035.txt
    aeaaa8bc18384cd483089c5441cdf73b:
      image_group_id: I1PD36107
      title: ''
      volume_number: 35
      total_pages: 92
      base_file: v036.txt
    d51590ad779842e582e5121da3f5d70f:
      image_group_id: I1PD36108
      title: ''
      volume_number: 36
      total_pages: 88
      base_file: v037.txt
    8c062279ccd24fddaa3132499b27a66b:
      image_group_id: I1PD36109
      title: ''
      volume_number: 37
      total_pages: 98
      base_file: v038.txt
    786566c9f2d74164a07211560492ee5d:
      image_group_id: I1PD36110
      title: ''
      volume_number: 38
      total_pages: 92
      base_file: v039.txt
    16f4ef44f665425cb865b8ceab09bd14:
      image_group_id: I1PD36111
      title: ''
      volume_number: 39
      total_pages: 88
      base_file: v040.txt
    8ac0feaaf6644cd1922d6d47886c68e9:
      image_group_id: I1PD36112
      title: ''
      volume_number: 40
      total_pages: 88
      base_file: v041.txt
    d591570988244ae6a3183d11054bab7b:
      image_group_id: I1PD36113
      title: ''
      volume_number: 41
      total_pages: 94
      base_file: v042.txt
    19a4b4aecbee4850a6ab1485b0ba342d:
      image_group_id: I1PD36114
      title: ''
      volume_number: 42
      total_pages: 100
      base_file: v043.txt
    dbe3f34a87a640288cf5b28e755924f5:
      image_group_id: I1PD36115
      title: ''
      volume_number: 43
      total_pages: 92
      base_file: v044.txt
    9dc0e9f93ddb4b2c8dc599ed8e67a1e5:
      image_group_id: I1PD36116
      title: ''
      volume_number: 44
      total_pages: 88
      base_file: v045.txt
    8fb0e8fd13f64227b725fa3900c0d95f:
      image_group_id: I1PD36117
      title: ''
      volume_number: 45
      total_pages: 94
      base_file: v046.txt
    772eb01532684b34bbab5a26b4a76ef6:
      image_group_id: I1PD36118
      title: ''
      volume_number: 46
      total_pages: 92
      base_file: v047.txt
    5873d2d8f19c4d73bbbf0ddab2792225:
      image_group_id: I1PD36119
      title: ''
      volume_number: 47
      total_pages: 94
      base_file: v048.txt
    a9a36f720aa84a1bae14638f374dcb60:
      image_group_id: I1PD36120
      title: ''
      volume_number: 48
      total_pages: 94
      base_file: v049.txt
    c3f058722e2e465abcbd8984256b1abd:
      image_group_id: I1PD36121
      title: ''
      volume_number: 49
      total_pages: 94
      base_file: v050.txt
    95e1f0e95b3a442190db69ddb48d7aa9:
      image_group_id: I1PD36122
      title: ''
      volume_number: 50
      total_pages: 94
      base_file: v051.txt
